noinst_PROGRAMS =
noinst_PROGRAMS += test-gom-adapter
noinst_PROGRAMS += test-gom-repository

TEST_PROGS += test-gom-adapter
TEST_PROGS += test-gom-repository

test_gom_adapter_SOURCES = $(top_srcdir)/tests/test-gom-adapter.c
test_gom_adapter_CPPFLAGS = $(GIO_CFLAGS) $(GOBJECT_CFLAGS)
test_gom_adapter_LDADD = $(GIO_LIBS) $(GOBJECT_LIBS) $(top_builddir)/libgom-1.0.la

test_gom_repository_SOURCES = $(top_srcdir)/tests/test-gom-repository.c
test_gom_repository_CPPFLAGS = $(GIO_CFLAGS) $(GOBJECT_CFLAGS)
test_gom_repository_LDADD = $(GIO_LIBS) $(GOBJECT_LIBS) $(top_builddir)/libgom-1.0.la
